[double_click.sh]
command = "open"
args = [
  "$FOCUSED"
]

[bindings.Enter.sh]
command = "open"
args = [
  "$FOCUSED"
]

[bindings.q]
quit = {}

[bindings.Up]
move = -1
[bindings.Down]
move = 1

[bindings.Right]
expand = {}
[bindings.Left]
collapse = {}

[bindings.']']
scroll = 1
[bindings.'[']
scroll = -1

[folder]
icon = ""
color = "blue"
text_color = "blue"

[style]
# Misc
"*.toml" = { icon = "" }
"*.conf" = { icon = "" }
"*.md" = { icon = "" }
"*.lock" = { icon = "", color = "red" }

# Programming Languages
"*.rs" = { icon = "", color = "red" }
"*.py" = { icon = "", color = "red" }
"*.go" = { icon = "", color = "red" }
"*.java" = { icon = "", color = "red" }

# Special
".gitignore" = { icon = "" }
"makefile" = { icon = "" }
".git" = { icon = "", color = "blue" }
".github" = { icon = "", color = "blue" }
"readme.md" = { icon = "", color = "red" }
".env" = {icon = ""}
